### PR TITLE
Optimize integer tag manipulation

### PR DESCRIPTION
**Pull request by waywardmonkeys**
This is an experiment to address what is discussed in issue #897.

### CODE REVIEW

**Comment by waywardmonkeys** [comment]
(I think this is for discussion for now rather than merging right away.)

**Comment by waywardmonkeys** [comment]
Some open questions:

* Should we also modify ``insert-integer-tag``?
* Does it matter that ``strip-integer-tag`` is no longer idempotent?

**Comment by housel** [comment]
- Yes, I think we should do both
- I don't think it matters; "strip" should mean "strip"

Any conclusions on what effect this has on the generated C code?

**Comment by waywardmonkeys** [comment]
I don't have performance numbers but the disassemblies that I put in the associated issue #897 are from the C back-end.

**Comment by waywardmonkeys** [comment]
I think we can defer making this an actual compiler primitive until such a thing is actually needed.

**Comment by waywardmonkeys** [comment]
This has been updated and should be ready for merging. It makes it through a 3 stage bootstrap on Mac OS X for me.

**Pull request merged**
