### PR TITLE
deleted similar file versions

### LINKED ISSUE #1100: Two versions of duim-resource-example
sources/app/duim-resource-example (soon to be moved to sources/examples/gui/duim-resource-example) and sources/duim/examples/resources appear to be slightly different versions of the same thing.  Figure out which one can be deleted, and delete it.

### PR DESCRIPTION
**Pull request by krush11**
fixes #1100 
deleted files in sources/examples/gui/duim-resource-example

### CODE REVIEW

**Comment by pedro-w** [comment]
From reading #1100 I'm not sure this is deleting the right files.

**Comment by krush11** [comment]
As i read in #1100 the files deleted in [`f91a902`](https://github.com/dylan-lang/opendylan/commit/f91a902892926f2541e6c2a4d23b012b7c61e443) were redirected to sources/examples/gui/duim-resource-example. This redirected files were still similar to the ones in sources/duim/examples/resources. So i deleted the files in sources/examples/gui/duim-resource-example

**Comment by pedro-w** [comment]
> So i deleted the files in sources/examples/gui/duim-resource-example

But there is already no `duim-resource-example` in [/sources/examples/gui](https://github.com/dylan-lang/opendylan/tree/master/sources/examples/gui)
Could you just explain in a bit more detail? Thanks!

**Comment by krush11** [comment]
> But there is already no `duim-resource-example` in [/sources/examples/gui](https://github.com/dylan-lang/opendylan/tree/master/sources/examples/gui)

sry wrong directory. It should have been [opendylan/sources/examples/gui/duim-gl-demo/](https://github.com/dylan-lang/opendylan/tree/master/sources/examples/gui/duim-gl-demo). My bad

**Comment by pedro-w** [comment]
For info, browsing the file history at  30b4a9192eecf4f5458c88f3901866af9dc1cf90 (the parent of f91a902892926f2541e6c2a4d23b012b7c61e443)

https://github.com/dylan-lang/opendylan/tree/30b4a9192eecf4f5458c88f3901866af9dc1cf90/sources/app/duim-resource-example
and
https://github.com/dylan-lang/opendylan/tree/30b4a9192eecf4f5458c88f3901866af9dc1cf90/sources/duim/examples/resources

and the former was deleted in f91a902892926f2541e6c2a4d23b012b7c61e443, with the comment 

    "In particular, sources/app/duim-resource-example appears to be an old
    version of sources/duim/examples/resources, so I deleted it. The
    sources/duim version is what's used in admin/builds/Makefile."

Also, `duim_gl_demo` is not duplicated anywhere, so this should not be deleted.

Therefore I think #1100 is fixed even without this PR.

**Comment by krush11** [comment]
great then i will look for something else i can contribute to

**Comment by cgay** [comment]
@krush11 there's a list of potential projects here: https://github.com/dylan-lang/opendylan/wiki
Of course looking at the bug lists works too...

**Pull request closed without merging**
