### PR TITLE
Fix bug in dfmc-reader:skip-multi-line-comments

### PR DESCRIPTION
**Pull request by cgay**
3-stage-bootstrap and dfmc-reader-test-suite pass

### CODE REVIEW

**Comment by housel** [comment]
It seems to me that the lexer is doing what it's specified to do by the DRM (i.e., it's not a bug per se), and that this is changing the spec as well as the implementation. I worry that it may be opening a can of worms, but in any case perhaps a DEP would be in order.

**Comment by cgay** [comment]
Ah, I see, because the spec is silent about what to do if `//` is inside of a string. I made the assumption that `/* */` should be able to comment out arbitrary code, but as you say, that's only an assumption. ok, I'll write a DEP.

Can you be more specific about the worms? Just a generalized worry about delimited comments having to do more complex parsing? I couldn't think of anything other than strings that would cause a problem.

**Comment by housel** [comment]
Another worm I thought of, for instance what should happen if you comment out `dylan/*` ?

**Comment by cgay** [comment]
ok, fair point. It wouldn't be hard to make `skip-multi-line-comment` ensure that `/*` and `//` are not adjacent to an identifier, but how big is this can of worms...

I feel pretty strongly that one should be able to comment out arbitrary sequences of complete fragments and expect the compiler to act as if there's nothing there, so I'm inclined to push ahead and see if we can fix these cases. I've always found, for example, that in languages that don't allow nested `/* */` comments they are basically useless. I'm more likely to just use line comments on large regions of code, "just in case". (We're already in better shape than that, thankfully.)

**Pull request closed without merging**
